// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "259284b1-4e2a-4c92-b20a-04f20b13cd1f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLedTurnOnChange();
void onUserControlChange();

int distance_cm;
int light_intensity;
bool led_status;
bool led_turn_on;
bool user_control;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(distance_cm, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(light_intensity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led_status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(led_turn_on, READWRITE, ON_CHANGE, onLedTurnOnChange);
  ArduinoCloud.addProperty(user_control, READWRITE, ON_CHANGE, onUserControlChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
